Mila.Módulo({
  define:"Mila.Evento.Tecla",
  necesita:["../tipo"]
});

Mila.Evento.Tecla.codigoEventoJs = function(eventoJs) {
  // Este es un código equivalente al scancode (con un poco más de detalle porque distingue, por ejemplo ctrl-izq y ctrl-der).
  // Representa a una tecla del teclado pero el nombre no necesariamente coincide con lo que esa tecla genera al escribir, ya que
  // es independiente de la distribución del teclado seleccionada.
  return eventoJs.code;
};

Mila.Evento.Tecla.scanCode = {
  // Letras
  LetraQ:"KeyQ",
  LetraW:"KeyW",
  LetraE:"KeyE",
  LetraR:"KeyR",
  LetraT:"KeyT",
  LetraY:"KeyY",
  LetraU:"KeyU",
  LetraI:"KeyI",
  LetraO:"KeyO",
  LetraP:"KeyP",
  LetraA:"KeyA",
  LetraS:"KeyS",
  LetraD:"KeyD",
  LetraF:"KeyF",
  LetraG:"KeyG",
  LetraH:"KeyH",
  LetraJ:"KeyJ",
  LetraK:"KeyK",
  LetraL:"KeyL",
  LetraZ:"KeyZ",
  LetraX:"KeyX",
  LetraC:"KeyC",
  LetraV:"KeyV",
  LetraB:"KeyB",
  LetraN:"KeyN",
  LetraM:"KeyM",
  // Números
  Dígito1:"Digit1",
  Dígito2:"Digit2",
  Dígito3:"Digit3",
  Dígito4:"Digit4",
  Dígito5:"Digit5",
  Dígito6:"Digit6",
  Dígito7:"Digit7",
  Dígito8:"Digit8",
  Dígito9:"Digit9",
  Dígito0:"Digit0",
  // Control
  FlechaArriba:"ArrowUp",
  FlechaAbajo:"ArrowDown",
  FlechaIzquierda:"ArrowLeft",
  FlechaDerecha:"ArrowRight",
  Espacio:"Space",
  Enter:"Enter",
  Borrar:"Backspace",
  Suprimir:"Delete",
  Escape:"Escape",
  Inicio:"Home",
  Fin:"End",
  PáginaAnterior:"PageUp",
  PáginaSiguiente:"PageDown",
  Tabulado:"Tab",
  BloquearMayúsculas:"CapsLock",
  Insertar:"Insert",
  MenúContextual:"ContextMenu",
  // Pad Numérico
  BloquearPadNumérico:"NumLock",
  PadNumérico9:"Numpad9",
  PadNumérico8:"Numpad8",
  PadNumérico7:"Numpad7",
  PadNumérico6:"Numpad6",
  PadNumérico5:"Numpad5",
  PadNumérico4:"Numpad4",
  PadNumérico3:"Numpad3",
  PadNumérico2:"Numpad2",
  PadNumérico1:"Numpad1",
  PadNumérico0:"Numpad0",
  PadNuméricoMás:"NumpadAdd",
  PadNuméricoMenos:"NumpadSubtract",
  PadNuméricoPor:"NumpadMultiply",
  PadNuméricoDividido:"NumpadDivide",
  PadNuméricoPunto:"NumpadDecimal",
  PadNuméricoEnter:"NumpadEnter",
  // Modificadores
  AltIzquierdo:"AltLeft",
  AltDerecho:"AltRight",
  ControlIzquierdo:"ControlLeft",
  ControlDerecho:"ControlRight",
  ShiftIzquierdo:"ShiftLeft",
  ShiftDerecho:"ShiftRight",
  // Función
  F1:"F1",
  F2:"F2",
  F3:"F3",
  F4:"F4",
  F5:"F5",
  F6:"F6",
  F7:"F7",
  F8:"F8",
  F9:"F9",
  F10:"F10",
  F11:"F11",
  F12:"F12",
  // Ojo. Los que siguen dependen de la distribución. Acá uso la distribución latina.
  Pipe:"Backquote",
  Comilla:"Minus",
  AbreInterrogación:"Equal",
  Tilde:"BracketLeft",
  Más:"BracketRight",
  AbreLlave:"Quote",
  CierraLlave:"Backslash",
  Guión:"Slash",
  Punto:"Period",
  Coma:"Comma",
  Menor:"IntlBackslash"
};